s/TRINKET/tool_FinvirsTrinket/g
s/EYE/tool_AntiquariansEye/g
s/RELICSENTINEL/tool_RelicOfTheSentinel/g

s/TYTHIS/assistant_TythisAndromo/g
s/PIRHARRI/assistant_Pirharri/g
s/NUZHIMEH/assistant_Nuzimeh/g
s/EZABI/assistant_Ezabi/g
s/FEZEZ/assistant_Fezez/g
s/BARON/assistant_BaronJangleplume/g
s/PEDDLER/assistant_PeddlerOfPrizes/g
s/BASTIAN/companion_BastianHallix/g
s/MIRRI/companion_MirriElendis/g
s/ARMORY/assistant_Ghrashorog/g

s/NIRNROOTWINE/memento_NirnrootWine/g
s/BONESNAP/memento_BonesnapBindingStone/g
s/WRATHFLAME/memento_MalacathsWrathfulFlame/g
s/ILLCOIN/memento_CoinOfIllusoryRiches/g
s/STORMATRO/memento_StormAtronachTransform/g
s/JUGGKNIVES/memento_JugglersKnives/g
s/TSHARD/memento_TwilightShard/g
s/LIGHTNINGSTICK/memento_NeramosLightningStick/g
s/KICKBALL/memento_KickBall/g
s/RAINBOW/memento_PrismaticBannerRibbon/g
s/DRAGONFLIGHT/memento_DragonFlightIllusionGem/g
s/DRAGONHORN/memento_DragonhornCurio/g
s/WALLLIFE/memento_WallOfLifeBrush/g
s/TOTEM/memento_RitualCircleTotem/g
s/CAMPFIRE/memento_CampfireKit/g
s/MOSTLYSTABLE/memento_MostlyStableJugglingPotions/g
s/CANDLEFLY/memento_TemproaryCandleflyLantern/g
s/VOIDSHARD/memento_VoidShard/g
s/INFCLEATS/memento_InfernoCleats/g
s/DECCOIN/memento_ImpartialDecisionCoin/g
s/MEM_WITCH_BONFIRE/memento_WitchsBonfireDust/g
s/AGONYMIUM/memento_AgonymiumStone/g

s/MUDBALL/throwable_MudBallPouch/g
s/BLOSSOMS/throwable_CherryBlossomBranch/g
s/SNOWBALL/throwable_EverlastingSnowball/g
s/MURDSTRIKE/throwable_MurderousStrike/g
